### ISSUE TITLE
UnicodeDecodeError in long running request traceback

### ISSUE THREAD

**Issue by keul** [collective/haufe.requestmonitoring#5]
We found this traceback in the log.

    	2014-09-09 14:11:12,506 ERROR RequestMonitor handler exception for dumper
	Traceback (most recent call last):
	  File "/opt/production4/eggs/haufe.requestmonitoring-0.4.0-py2.7.egg/haufe/requestmonitoring/monitor.py", line 78, in run
	    handler(monitorTime, pending)
	  File "/opt/production4/eggs/haufe.requestmonitoring-0.4.0-py2.7.egg/haufe/requestmonitoring/monitor.py", line 98, in __call__
	    state._check(monitorTime, requests)
	  File "/opt/production4/eggs/haufe.requestmonitoring-0.4.0-py2.7.egg/haufe/requestmonitoring/monitor.py", line 116, in _check
	    handler._handler(req, self, requests)
	  File "/opt/production4/eggs/haufe.requestmonitoring-0.4.0-py2.7.egg/haufe/requestmonitoring/DumpTraceback.py", line 63, in handler
	    stack_trace,
	UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 171: ordinal not in range(128)

It's difficult to say when/how this happen.

**Comment by thet** [comment]
@keul can you verify, if the unicodedecodeerror is gone with my branch?

**Comment by keul** [comment]
@thet I don't have a way to reproduce the error. We found the traceback in a old log and never been able to reproduce it in any way (if facts this open issue was probably not much useful).

If you think you closed the issue we can probably just close!

**Comment by keul** [comment]
Hope this has been closed by https://github.com/collective/haufe.requestmonitoring/pull/7

**Comment by thet** [comment]
ok, fine. tnx for merging!
